[tools]
go = "1.24.3"

"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "2.1.6"
"go:github.com/goreleaser/goreleaser/v2" = "2.9.0"
"go:github.com/vektra/mockery/v3" = "3.5.0"
"go:golang.org/x/tools/cmd/goimports" = "0.34.0"
