# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build the binary
    cmds:
      - go build -o gorocket .
      - echo "Binary built successfully - gorocket"
  
  # Testing tasks
  test:
    desc: Run all tests
    cmds:
      - go test ./...
  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"
  
  # Mock management
  mocks:
    desc: Generate mocks for testing
    cmds:
      - mockery
  
  # Code quality
  format:
    desc: Format Go code with goimports
    cmds:
      - goimports -w .
  
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run
