build:
  # ldflags: "-s -w"  # Optional: linker flags for binary optimization
  targets:
    - os: linux
      arch: [amd64, arm64]
    - os: darwin
      arch: [amd64, arm64]
    - os: windows
      arch: [amd64, arm64]

# brew:
#   repository:
#     owner:
#     name: