// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/koki-develop/gorocket/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// ConfigExists provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) ConfigExists() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigProvider_ConfigExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigExists'
type MockConfigProvider_ConfigExists_Call struct {
	*mock.Call
}

// ConfigExists is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) ConfigExists() *MockConfigProvider_ConfigExists_Call {
	return &MockConfigProvider_ConfigExists_Call{Call: _e.mock.On("ConfigExists")}
}

func (_c *MockConfigProvider_ConfigExists_Call) Run(run func()) *MockConfigProvider_ConfigExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_ConfigExists_Call) Return(b bool) *MockConfigProvider_ConfigExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigProvider_ConfigExists_Call) RunAndReturn(run func() bool) *MockConfigProvider_ConfigExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDefaultConfig provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) CreateDefaultConfig() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateDefaultConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigProvider_CreateDefaultConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDefaultConfig'
type MockConfigProvider_CreateDefaultConfig_Call struct {
	*mock.Call
}

// CreateDefaultConfig is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) CreateDefaultConfig() *MockConfigProvider_CreateDefaultConfig_Call {
	return &MockConfigProvider_CreateDefaultConfig_Call{Call: _e.mock.On("CreateDefaultConfig")}
}

func (_c *MockConfigProvider_CreateDefaultConfig_Call) Run(run func()) *MockConfigProvider_CreateDefaultConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_CreateDefaultConfig_Call) Return(err error) *MockConfigProvider_CreateDefaultConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigProvider_CreateDefaultConfig_Call) RunAndReturn(run func() error) *MockConfigProvider_CreateDefaultConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultConfigData provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) GetDefaultConfigData() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultConfigData")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockConfigProvider_GetDefaultConfigData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultConfigData'
type MockConfigProvider_GetDefaultConfigData_Call struct {
	*mock.Call
}

// GetDefaultConfigData is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetDefaultConfigData() *MockConfigProvider_GetDefaultConfigData_Call {
	return &MockConfigProvider_GetDefaultConfigData_Call{Call: _e.mock.On("GetDefaultConfigData")}
}

func (_c *MockConfigProvider_GetDefaultConfigData_Call) Run(run func()) *MockConfigProvider_GetDefaultConfigData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetDefaultConfigData_Call) Return(bytes []byte) *MockConfigProvider_GetDefaultConfigData_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockConfigProvider_GetDefaultConfigData_Call) RunAndReturn(run func() []byte) *MockConfigProvider_GetDefaultConfigData_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConfig provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) LoadConfig() (*models.Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *models.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*models.Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *models.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigProvider_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockConfigProvider_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) LoadConfig() *MockConfigProvider_LoadConfig_Call {
	return &MockConfigProvider_LoadConfig_Call{Call: _e.mock.On("LoadConfig")}
}

func (_c *MockConfigProvider_LoadConfig_Call) Run(run func()) *MockConfigProvider_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_LoadConfig_Call) Return(config *models.Config, err error) *MockConfigProvider_LoadConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockConfigProvider_LoadConfig_Call) RunAndReturn(run func() (*models.Config, error)) *MockConfigProvider_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}
